import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import path from 'path';
import {defineConfig, loadEnv} from 'vite';
import {VitePWA} from 'vite-plugin-pwa';

export default defineConfig(({mode}) => {
  const env = loadEnv(mode, '.', '');
  return {
    // NOTE: GEMINI_API_KEY is intentionally NOT injected into the client bundle here.
    // No code in src/ currently calls the Gemini API - the dependency/env var were
    // leftover AI Studio scaffolding. If an AI-assisted feature is built later, call it
    // through an authenticated Firebase Cloud Function that holds the key server-side,
    // never via a build-time `define` (which would ship the secret inside the compiled
    // app - a real risk once this is packaged as an iOS/Android binary).
    plugins: [
      react(),
      tailwindcss(),
      VitePWA({
        registerType: 'autoUpdate',
        includeAssets: ['favicon.png'],
        manifest: {
          name: 'Railway Signalling Logbook',
          short_name: 'Signalling Logbook',
          description: 'Digital logbook for railway signalling professionals to track work history, equipment maintenance, and certifications.',
          theme_color: '#0f2a4a',
          background_color: '#ffffff',
          display: 'standalone',
          start_url: '/',
          // Generated by `npx capacitor-assets generate` from resources/icon.png
          // (see Phase 1 of MOBILE_DEPLOYMENT_PLAN.md). Still a placeholder "RSL"
          // wordmark on navy - swap resources/icon.png + resources/splash.png for
          // real branding and re-run the generator before shipping.
          icons: [
            { src: 'icons/icon-48.webp', sizes: '48x48', type: 'image/webp', purpose: 'any maskable' },
            { src: 'icons/icon-72.webp', sizes: '72x72', type: 'image/webp', purpose: 'any maskable' },
            { src: 'icons/icon-96.webp', sizes: '96x96', type: 'image/webp', purpose: 'any maskable' },
            { src: 'icons/icon-128.webp', sizes: '128x128', type: 'image/webp', purpose: 'any maskable' },
            { src: 'icons/icon-192.webp', sizes: '192x192', type: 'image/webp', purpose: 'any maskable' },
            { src: 'icons/icon-256.webp', sizes: '256x256', type: 'image/webp', purpose: 'any maskable' },
            { src: 'icons/icon-512.webp', sizes: '512x512', type: 'image/webp', purpose: 'any maskable' },
          ],
        },
        workbox: {
          globPatterns: ['**/*.{js,css,html,ico,png,svg}'],
        },
      }),
    ],
    resolve: {
      alias: {
        '@': path.resolve(__dirname, '.'),
      },
    },
    server: {
      // HMR is disabled in AI Studio via DISABLE_HMR env var.
      // Do not modifyâfile watching is disabled to prevent flickering during agent edits.
      hmr: process.env.DISABLE_HMR !== 'true',
    },
  };
});
